In [1]:
import numpy as np
x = np.array([[0.093, 0.1939, -1.0649, 0.4476, -2.0769],
[-1.8024, 0.3696, 0.7796, -1.0346, 0.473],
[0.5593, -2.5067, -2.1275, 0.5548, -1.6639]])

y = np.array([1, 2, 3])

In [35]:
def softmax(x):
    t = np.exp(x)
    for i in range(len(x)):
        t[i,:] = t[i,:]/np.sum(np.exp(x[i,:]))
    return t

def cross_entropy(x, y):
	Y = np.zeros([len(y), x.shape[1]])
	for i in range(len(y)):
		Y[i, y[i]] = 1

	log_softmax = np.log(softmax(x))
	cross_ent = 0;
	cross_ent = np.sum(np.dot(log_softmax, Y.T))
	return -cross_ent

In [42]:
np.sum(softmax(x)[0,:])

1.0

In [43]:
Y = np.zeros([len(y), x.shape[1]])
for i in range(len(y)):
    Y[i, y[i]] = 1
Y

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [44]:
np.log(softmax(x))

array([[-1.37627194, -1.27537194, -2.53417194, -1.02167194, -3.54617194],
       [-3.55209156, -1.38009156, -0.97009156, -2.78429156, -1.27669156],
       [-0.79682135, -3.86282135, -3.48362135, -0.80132135, -3.02002135]])

In [47]:
log_softmax = np.log(softmax(x))
np.dot(log_softmax, Y.T)

array([[-1.27537194, -2.53417194, -1.02167194],
       [-1.38009156, -0.97009156, -2.78429156],
       [-3.86282135, -3.48362135, -0.80132135]])

In [40]:
cross_entropy(x, y)

18.11345455737564

In [9]:
Y = np.zeros([len(y),max(y) + 1])
Y.shape

(3, 4)